build:  objects.cpp	client_udp.cpp server_udp.cpp network.cpp physic.cpp list.cpp font.cpp menu.cpp main.cpp
	g++ -o game objects.cpp client_udp.cpp server_udp.cpp network.cpp physic.cpp list.cpp font.cpp menu.cpp main.cpp `sdl2-config --cflags --libs` -lSDL2_ttf -lpthread -I. -Wall

